services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
      - "5173:5173"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db;Database=OrderManagerDb;User=sa;Password=Your_password123;Encrypt=False;"
      ConnectionStrings__SetupConnection: "Server=db;Database=master;User=sa;Password=Your_password123;Encrypt=False;"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
